### ISSUE TITLE
How to extract the multiplicity between two selected vertices?

### ISSUE THREAD

**Issue by DEXTERcyy** [QuantumBFS/Multigraphs.jl#3]
I want  to out put the number of edges between two vertices with no idea how.

**Comment by Roger-luo** [comment]
but the point is which object do you want to attach to? All the edges from vertex A and vertex B?

**Comment by ChenZhao44** [comment]
The multiplicity of a multigraph `mg` between `v1` and `v2` can be access with `mg.adjmx[v1, v2]`.
But now there is no API for this. We will add this later.

**Comment by DEXTERcyy** [comment]
got it
` G=Multigraph(4);
 add_edge!(G,1,2,2)
 add_edge!(G,3,2,2)
 add_edge!(G,1,4,1)
 add_edge!(G,4,3,2)
length(collect(edges(G))[1])
`
this is what i want.
